site:
  title: Serverless Workflow Guides
  start_page: serverlessworkflow::index.adoc
antora:
  extensions:
    - require: '@antora/lunr-extension'
content:
  sources:
    - url: git@github.com:akumar074/test-action.git
      branches: [main, test-release]
      start_path: serverlessworkflow
ui:
  bundle:
    url: ./antora/ui-bundle.zip
    snapshot: true
  supplemental_files: ./antora/supplemental-ui
asciidoc:
  extensions:
  - asciidoctor-emoji
  attributes:
    linkattrs: ''
    toc: ~
