name: Serverless Workflow Docs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: serverlessworkflow/antora-playbook.yml