name: Serverless Workflow Docs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: export DOCSEARCH_ENABLED=true
      - run: export DOCSEARCH_ENGINE=lunr
      - run: export NODE_PATH="$(npm -g root)"
      - run: npm -v
      - run: npm i -g @antora/cli @antora/site-generator @antora/lunr-extension
      - run: antora --extension @antora/lunr-extension --fetch antora-playbook.yml --stacktrace
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: test-action
          directory: build/site
          gitHubToken: ${{ secrets.GH_ACTION }}
